---
title: Title here
subtitle: Do you have a subtitle? If so, write it here
titlerunning: Short form of title (if too long for head)
authorrunning:
  Short form of author list if too long for running head
thanks: |
  Grants or other notes about the article that should go
  on the front page should be placed here. General
  acknowledgments should be placed at the end of the article.
authors:
  - name: Author 1
    address: Department of YYY, University of XXX
    email: abc@def
  - name: Author 2
    address: Department of ZZZ, University of WWW
    email: djf@wef
keywords:
  - key
  - dictionary
  - word
MSC:
  - MSC code 1
  - MSC code 2    
abstract: |
  The text of your abstract.  150 -- 250 words.
bibliography: reliability.bib
header-includes:
    - \usepackage{longtable}
    - \usepackage{booktabs}


output: rticles::springer_article

---

```{r child = '01-intro.Rmd'}
```

```{r child = '02-methods.Rmd'}
```

```{r child = '03-results.Rmd'}
```

```{r child = '04-discussion.Rmd'}
```